### ISSUE TITLE
test_e2e_12_mef_eline.TestE2EMefEline::test_delete_circuit_id has been flaky

### ISSUE THREAD

**Issue by viniarck** [amlight/kytos-end-to-end-tests#149]
This test case failed on yesterday's CI execution, it's been flaky:

```
____________________ TestE2EMefEline.test_delete_circuit_id ____________________
self = <tests.test_e2e_12_mef_eline.TestE2EMefEline object at 0x7f35461dd6a0>
circuit_id = '5bcd507b1e6c49'
    def test_delete_circuit_id(self, circuit_id):
        """ Test circuit removal action. """
    
        # Delete the circuit
        api_url = KYTOS_API + '/mef_eline/v2/evc/' + circuit_id
        response = requests.delete(api_url)
        assert response.status_code == 200, response.text
    
        time.sleep(10)
    
        # Verify circuit removal by
        # listing all the circuits stored
        api_url = KYTOS_API + '/mef_eline/v2/evc/'
        response = requests.get(api_url)
        assert response.status_code == 200, response.text
        data = response.json()
        assert data == {}
    
        # Verify that the flow is not in the flow table
        s1 = self.net.net.get('s1')
        flows_s1 = s1.dpctl('dump-flows')
        # Each switch had BASIC_FLOWS flows + 02 for the EVC (ingress + egress)
        # at this point the flow number should be reduced to BASIC_FLOWS
>       assert len(flows_s1.split('\r\n ')) == BASIC_FLOWS
E       AssertionError: assert 5 == 3
E        +  where 5 = len([' cookie=0x0, duration=22.370s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONT...n=25.436s, table=0, n_packets=16, n_bytes=672, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'])
E        +    where [' cookie=0x0, duration=22.370s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONT...n=25.436s, table=0, n_packets=16, n_bytes=672, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'] = <built-in method split of str object at 0x7f3528024a50>('\r\n ')
E        +      where <built-in method split of str object at 0x7f3528024a50> = ' cookie=0x0, duration=22.370s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONTR...on=25.436s, table=0, n_packets=16, n_bytes=672, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535\r\n'.split
tests/test_e2e_12_mef_eline.py:389: AssertionError
```

**Comment by jab1982** [comment]
Ideally, we were suppose to assert just the flows we expect to see after our request, including confirming the matches and actions. However, since it will be a lot of work for now, why not just counting the number of flows installed before the request and count again after the request and asset the difference?

**Comment by viniarck** [comment]
> Ideally, we were suppose to assert just the flows we expect to see after our request, including confirming the matches and actions. However, since it will be a lot of work for now, why not just counting the number of flows installed before the request and count again after the request and asset the difference?

@jab1982 recently there was a discussion to follow this approach only check what you need or what the test focus on leveraging cookie prefix https://github.com/amlight/kytos-end-to-end-tests/pull/133#discussion_r943917230, btw let me map on an new issue, which also decouples dependency on basic_flows. The idea of asserting the difference is a possibility, but if it gets flaky again in the future, you won't exactly know what's missing or extra, making it a bit hard to figure out what went wrong. To address this last point, it was mapped this enhancement on issue #151 that should land soon, thanks for your suggestion and inputs.
