### ISSUE TITLE
create a test to validate the installation of a EVC when the switch suddenly disconnect

### ISSUE THREAD

**Issue by italovalcy** [amlight/kytos-end-to-end-tests#60]
We should have a test to evaluate how Kytos behaves when the switch suddenly disconnects during the creation of an EVC. Apparently, the flow manager dont validated if the switch is active and returns error 500 when tries to create a flow on a disconnected switch. In the same way, mef_eline dont validate the return code from flow_manager.

We should create two tests to validate mef_eline and flow_manager.

**Comment by gretelliz** [comment]
This issue was fixed with PR #49

**Comment by italovalcy** [comment]
@gretelliz, I believe you mean to refer to PR kytos-ng/flow_manager#49 right?
